/*
 * Shared symbol/code/organization reference — the single source of truth
 * for both the standalone /awareness page and the in-app Awareness tab's
 * card grid. Deliberately text-only, no imagery of the symbols themselves
 * (see the "why this page describes rather than shows" copy below).
 */
window.DXMAP_AWARENESS = {
  en: {
    eyebrow: "Awareness", h1: "Recognizing far-right symbols, gestures, and coded language.",
    lede: "Not a catalog to browse for its own sake — a reference for recognizing what you're looking at, so you can report it, avoid it, or just understand what you saw.",
    whyTitle: "Why this describes rather than shows",
    whyBody: "You won't find images of the symbols here. Text descriptions are enough for recognition, and reproducing the imagery itself — even for education — risks doing the one thing this project exists to stop. Everything below is grounded in Germany's actual statute references (the same ones the map uses to classify reports), not a general internet list.",
    symbolsEyebrow: "Banned under § 86a StGB", symbolsTitle: "Symbols and gestures",
    symbolsLede: "Public use or display of these is a criminal offense in Germany, outside narrow exceptions for art, science, research, or reporting on history.",
    symbols: [
      { code: "§ 86a StGB", title: "The swastika (Hakenkreuz)", body: "The most widely recognized Nazi symbol. Any orientation, any context outside the legal exceptions above, is covered by the ban — this includes stylized or partially-obscured versions used to evade moderation." },
      { code: "§ 86a StGB", title: "SS runes and the death's head (Totenkopf)", body: "The double lightning-bolt \"Sig rune\" associated with the SS, and the skull-and-crossbones insignia used by SS units, are both banned symbols under the same statute." },
      { code: "§ 86a StGB", title: "The Hitler salute and \"Sieg Heil\"", body: "The raised-arm salute, and the phrase \"Sieg Heil\" spoken or written publicly, are both criminalized gestures/speech — not just symbols in the graphic sense." },
      { code: "§ 86a StGB", title: "The Reichskriegsflagge (war ensign)", body: "Specific historical war-flag variants (particularly the 1938 pattern with the Iron Cross and swastika) are banned; the flag has been adopted as a stand-in symbol by later far-right groups specifically because the plain naval-ensign version is not automatically illegal — context and specific variant matter." },
    ],
    codesEyebrow: "Coded language", codesTitle: "Numbers and letter codes",
    codesLede: "Numeric substitution ciphers let the same message travel as a tattoo, a license plate, or a screen name without tripping an obvious keyword filter. None of these numbers are illegal on their own — context is what matters — but recognizing the pattern is the point.",
    codes: [
      { k: "88", v: "H is the 8th letter — \"HH\" = \"Heil Hitler\"" },
      { k: "18", v: "\"AH\" = Adolf Hitler's initials" },
      { k: "14 / 1488", v: "The \"14 words\" white-supremacist slogan, often paired with 88" },
      { k: "28", v: "\"BH\" — Blood & Honour, a banned network" },
    ],
    orgEyebrow: "Organizations", orgTitle: "Banned associations",
    orgBody: "Germany's federal and state governments can and do ban specific far-right organizations under the Vereinsgesetz (Associations Act) — continuing to act for or promote a banned association is itself a separate offense (§ 20 VereinsG). Which organizations are currently banned changes over time as courts and interior ministries act — the map's own statute reference stays current with what's classifiable, but for the authoritative, up-to-date list, the Bundesamt für Verfassungsschutz (Federal Office for the Protection of the Constitution) publishes one directly.",
    orgLink: "verfassungsschutz.de →",
    safetyTitle: "If you see one of these",
    safetyBody: "Graffiti, a sticker, a symbol in public — document it from a safe distance, on public property, without confronting anyone. If it's a crime in progress or you feel unsafe, call the police (110) first. Otherwise, the map has a reporting flow built for exactly this.",
    fileBtn: "File a report →",
    footer: "Sources: German Strafgesetzbuch (StGB) §§ 86, 86a, and the Vereinsgesetz. This documents publicly available legal facts for recognition and safety — it is not legal advice.",
  },
  de: {
    eyebrow: "Aufklärung", h1: "Rechtsextreme Symbole, Gesten und Code-Sprache erkennen.",
    lede: "Kein Katalog zum Durchstöbern, sondern ein Nachschlagewerk, um zu erkennen, was man vor sich hat — um es zu melden, zu meiden oder einfach zu verstehen, was man gesehen hat.",
    whyTitle: "Warum hier beschrieben statt gezeigt wird",
    whyBody: "Hier finden sich keine Abbildungen der Symbole. Textbeschreibungen reichen zur Erkennung aus, und die Bilder selbst zu reproduzieren — auch zu Bildungszwecken — riskiert genau das, was dieses Projekt verhindern soll. Alles Folgende stützt sich auf die tatsächlichen deutschen Gesetzesparagraphen (dieselben, nach denen die Karte Meldungen einordnet), nicht auf eine allgemeine Internetliste.",
    symbolsEyebrow: "Verboten nach § 86a StGB", symbolsTitle: "Symbole und Gesten",
    symbolsLede: "Die öffentliche Verwendung oder Zurschaustellung ist in Deutschland eine Straftat, mit engen Ausnahmen für Kunst, Wissenschaft, Forschung oder Berichterstattung über Geschichte.",
    symbols: [
      { code: "§ 86a StGB", title: "Das Hakenkreuz", body: "Das bekannteste NS-Symbol. Jede Ausrichtung und jeder Kontext außerhalb der oben genannten gesetzlichen Ausnahmen fällt unter das Verbot — auch stilisierte oder teilweise verdeckte Versionen, die zur Umgehung von Moderation genutzt werden." },
      { code: "§ 86a StGB", title: "SS-Runen und Totenkopf", body: "Die doppelte Blitz-„Sig-Rune“ der SS sowie das Totenkopf-Abzeichen von SS-Einheiten sind beides nach demselben Paragraphen verbotene Symbole." },
      { code: "§ 86a StGB", title: "Der Hitlergruß und „Sieg Heil“", body: "Der ausgestreckte Arm als Gruß sowie der öffentlich gesprochene oder geschriebene Ausruf „Sieg Heil“ sind strafbare Gesten bzw. Äußerungen — nicht nur Symbole im grafischen Sinn." },
      { code: "§ 86a StGB", title: "Die Reichskriegsflagge", body: "Bestimmte historische Kriegsflaggen-Varianten (insbesondere die Fassung von 1938 mit Eisernem Kreuz und Hakenkreuz) sind verboten; die Flagge wurde von späteren rechtsextremen Gruppen als Ersatzsymbol übernommen, gerade weil die schlichte Marineflaggen-Version nicht automatisch illegal ist — Kontext und konkrete Variante entscheiden." },
    ],
    codesEyebrow: "Code-Sprache", codesTitle: "Zahlen- und Buchstabencodes",
    codesLede: "Numerische Ersatzchiffren lassen dieselbe Botschaft als Tattoo, Kennzeichen oder Nutzername reisen, ohne einen offensichtlichen Stichwortfilter auszulösen. Keine dieser Zahlen ist für sich genommen illegal — der Kontext entscheidet —, aber das Muster zu erkennen ist der Punkt.",
    codes: [
      { k: "88", v: "H ist der 8. Buchstabe — „HH“ = „Heil Hitler“" },
      { k: "18", v: "„AH“ = Adolf Hitlers Initialen" },
      { k: "14 / 1488", v: "Die „14 words“, ein Slogan weißer Vorherrschaft, oft mit 88 kombiniert" },
      { k: "28", v: "„BH“ — Blood & Honour, ein verbotenes Netzwerk" },
    ],
    orgEyebrow: "Organisationen", orgTitle: "Verbotene Vereinigungen",
    orgBody: "Bund und Länder können und verbieten konkrete rechtsextreme Organisationen nach dem Vereinsgesetz — das Fortführen oder Werben für eine verbotene Vereinigung ist selbst eine eigene Straftat (§ 20 VereinsG). Welche Organisationen aktuell verboten sind, ändert sich mit Gerichts- und Innenministeriumsentscheidungen — die Statutenreferenz der Karte bleibt aktuell in Bezug auf das Klassifizierbare, für die maßgebliche, aktuelle Liste veröffentlicht das Bundesamt für Verfassungsschutz jedoch direkt eine solche.",
    orgLink: "verfassungsschutz.de →",
    safetyTitle: "Wenn du so etwas siehst",
    safetyBody: "Graffiti, ein Aufkleber, ein Symbol im öffentlichen Raum — dokumentiere es aus sicherer Entfernung, auf öffentlichem Grund, ohne jemanden zu konfrontieren. Bei einer laufenden Straftat oder wenn du dich unsicher fühlst, ruf zuerst die Polizei (110). Ansonsten bietet die Karte einen Meldeweg genau dafür.",
    fileBtn: "Melden →",
    footer: "Quellen: deutsches Strafgesetzbuch (StGB) §§ 86, 86a, sowie das Vereinsgesetz. Dies dokumentiert öffentlich zugängliche Rechtstatsachen zur Erkennung und Sicherheit — es ist keine Rechtsberatung.",
  },
  fr: {
    eyebrow: "Sensibilisation", h1: "Reconnaître les symboles, gestes et langage codé d'extrême droite.",
    lede: "Pas un catalogue à parcourir pour lui-même — une référence pour reconnaître ce que vous voyez, afin de le signaler, de l'éviter, ou simplement de comprendre ce que vous avez vu.",
    whyTitle: "Pourquoi ceci décrit plutôt que ça ne montre",
    whyBody: "Vous ne trouverez pas d'images des symboles ici. Des descriptions textuelles suffisent pour la reconnaissance, et reproduire l'imagerie elle-même — même à des fins éducatives — risque de faire précisément ce que ce projet existe pour empêcher. Tout ce qui suit s'appuie sur les références statutaires réelles de l'Allemagne (les mêmes que celles utilisées par la carte pour classer les signalements), pas sur une liste internet générale.",
    symbolsEyebrow: "Interdit par le § 86a StGB", symbolsTitle: "Symboles et gestes",
    symbolsLede: "L'utilisation ou l'affichage public de ceux-ci est une infraction pénale en Allemagne, sauf exceptions étroites pour l'art, la science, la recherche ou le compte-rendu historique.",
    symbols: [
      { code: "§ 86a StGB", title: "La croix gammée (Hakenkreuz)", body: "Le symbole nazi le plus largement reconnu. Toute orientation, tout contexte hors des exceptions légales ci-dessus, est couvert par l'interdiction — y compris les versions stylisées ou partiellement masquées utilisées pour échapper à la modération." },
      { code: "§ 86a StGB", title: "Runes SS et tête de mort (Totenkopf)", body: "La double rune-éclair « Sig » associée à la SS, ainsi que l'insigne tête de mort utilisé par les unités SS, sont tous deux des symboles interdits par le même article." },
      { code: "§ 86a StGB", title: "Le salut hitlérien et « Sieg Heil »", body: "Le salut bras levé, ainsi que l'expression « Sieg Heil » prononcée ou écrite publiquement, sont tous deux des gestes/discours criminalisés — pas seulement des symboles au sens graphique." },
      { code: "§ 86a StGB", title: "Le Reichskriegsflagge (pavillon de guerre)", body: "Certaines variantes historiques du pavillon de guerre (notamment le modèle de 1938 avec la croix de fer et la croix gammée) sont interdites ; le drapeau a été adopté comme symbole de substitution par des groupes d'extrême droite plus récents précisément parce que la version simple de pavillon naval n'est pas automatiquement illégale — le contexte et la variante précise comptent." },
    ],
    codesEyebrow: "Langage codé", codesTitle: "Codes numériques et alphabétiques",
    codesLede: "Les chiffres de substitution numérique permettent au même message de voyager sous forme de tatouage, de plaque d'immatriculation ou de pseudonyme sans déclencher de filtre à mots-clés évident. Aucun de ces nombres n'est illégal en soi — le contexte est ce qui compte — mais reconnaître le motif est l'essentiel.",
    codes: [
      { k: "88", v: "H est la 8e lettre — « HH » = « Heil Hitler »" },
      { k: "18", v: "« AH » = les initiales d'Adolf Hitler" },
      { k: "14 / 1488", v: "Le slogan suprémaciste blanc des « 14 mots », souvent associé au 88" },
      { k: "28", v: "« BH » — Blood & Honour, un réseau interdit" },
    ],
    orgEyebrow: "Organisations", orgTitle: "Associations interdites",
    orgBody: "Les gouvernements fédéral et régionaux allemands peuvent interdire, et interdisent effectivement, des organisations d'extrême droite spécifiques en vertu du Vereinsgesetz (loi sur les associations) — continuer à agir pour ou promouvoir une association interdite constitue elle-même une infraction distincte (§ 20 VereinsG). Les organisations actuellement interdites évoluent au fil des décisions des tribunaux et des ministères de l'Intérieur — la référence statutaire de la carte reste à jour quant à ce qui est classable, mais pour la liste officielle et actualisée, le Bundesamt für Verfassungsschutz en publie une directement.",
    orgLink: "verfassungsschutz.de →",
    safetyTitle: "Si vous voyez l'un de ces éléments",
    safetyBody: "Un graffiti, un autocollant, un symbole en public — documentez-le à distance sûre, sur la voie publique, sans confronter personne. En cas de crime en cours ou si vous vous sentez en danger, appelez d'abord la police (110). Sinon, la carte dispose d'un parcours de signalement conçu exactement pour cela.",
    fileBtn: "Signaler →",
    footer: "Sources : Code pénal allemand (StGB) §§ 86, 86a, et le Vereinsgesetz. Ceci documente des faits juridiques publiquement disponibles à des fins de reconnaissance et de sécurité — ce n'est pas un conseil juridique.",
  },
  ar: {
    eyebrow: "التوعية", h1: "التعرّف على رموز اليمين المتطرف وإيماءاته ولغته المشفَّرة.",
    lede: "ليس فهرسًا للتصفح لذاته — بل مرجع للتعرّف على ما تراه، حتى تتمكن من الإبلاغ عنه أو تجنّبه أو ببساطة فهم ما شاهدته.",
    whyTitle: "لماذا يصف هذا بدل أن يُظهر",
    whyBody: "لن تجد صورًا للرموز هنا. الأوصاف النصية كافية للتعرّف، وإعادة إنتاج الصور نفسها — حتى لأغراض تعليمية — يخاطر بفعل الشيء ذاته الذي يسعى هذا المشروع لمنعه. كل ما يلي مستند إلى مواد القانون الألماني الفعلية (نفسها التي تستخدمها الخريطة لتصنيف البلاغات)، وليس إلى قائمة عامة من الإنترنت.",
    symbolsEyebrow: "محظور بموجب المادة 86a من قانون العقوبات", symbolsTitle: "الرموز والإيماءات",
    symbolsLede: "استخدام هذه الرموز أو عرضها علنًا يُعدّ جريمة في ألمانيا، باستثناءات ضيقة للفن والعلم والبحث أو التغطية التاريخية.",
    symbols: [
      { code: "المادة 86a", title: "الصليب المعقوف (Hakenkreuz)", body: "أكثر الرموز النازية شهرة. أي اتجاه أو سياق خارج الاستثناءات القانونية أعلاه يقع ضمن الحظر — بما في ذلك النسخ المُنمَّطة أو المموَّهة جزئيًا المستخدمة للتحايل على الإشراف." },
      { code: "المادة 86a", title: "رموز SS وجمجمة الموت (Totenkopf)", body: "رمز الصاعقة المزدوجة «Sig rune» المرتبط بقوات SS، وشعار الجمجمة والعظمتين المتقاطعتين الذي استخدمته وحدات SS، كلاهما رمزان محظوران بموجب المادة نفسها." },
      { code: "المادة 86a", title: "تحية هتلر وعبارة «Sieg Heil»", body: "تحية الذراع المرفوعة، وعبارة «Sieg Heil» المنطوقة أو المكتوبة علنًا، كلاهما إيماءة/خطاب مجرَّم — وليسا مجرد رمز بالمعنى الرسومي." },
      { code: "المادة 86a", title: "علم الرايخ الحربي (Reichskriegsflagge)", body: "نسخ تاريخية محددة من علم الحرب (خصوصًا نمط عام 1938 الذي يحمل الصليب الحديدي والصليب المعقوف) محظورة؛ وقد تبنّت جماعات يمين متطرف لاحقة هذا العلم كرمز بديل تحديدًا لأن نسخة العلم البحري البسيطة ليست محظورة تلقائيًا — السياق والنسخة المحددة هما ما يحدّدان ذلك." },
    ],
    codesEyebrow: "اللغة المشفَّرة", codesTitle: "الأرقام والرموز الحرفية",
    codesLede: "شفرات الاستبدال الرقمي تسمح بنقل الرسالة نفسها كوشم أو لوحة سيارة أو اسم مستخدم دون إثارة فلتر كلمات مفتاحية واضح. لا شيء من هذه الأرقام محظور بذاته — السياق هو ما يهم — لكن التعرّف على النمط هو المقصد.",
    codes: [
      { k: "88", v: "الحرف H هو الحرف الثامن — «HH» = «Heil Hitler»" },
      { k: "18", v: "«AH» = الحرفان الأولان من اسم أدولف هتلر" },
      { k: "14 / 1488", v: "شعار تفوّق العرق الأبيض «الكلمات الأربع عشرة»، غالبًا مقترن بـ88" },
      { k: "28", v: "«BH» — Blood & Honour، شبكة محظورة" },
    ],
    orgEyebrow: "المنظمات", orgTitle: "الجمعيات المحظورة",
    orgBody: "يمكن للحكومة الفيدرالية الألمانية وحكومات الولايات حظر منظمات يمين متطرف محددة بموجب قانون الجمعيات (Vereinsgesetz) — والاستمرار في العمل لصالح جمعية محظورة أو الترويج لها يُعدّ جريمة منفصلة بذاتها (المادة 20 من قانون الجمعيات). قائمة المنظمات المحظورة حاليًا تتغيّر مع قرارات المحاكم ووزارات الداخلية — يبقى مرجع الخريطة القانوني محدَّثًا وفق ما يمكن تصنيفه، لكن للحصول على القائمة الرسمية المحدَّثة، ينشر المكتب الاتحادي لحماية الدستور (Bundesamt für Verfassungsschutz) قائمة مباشرة.",
    orgLink: "verfassungsschutz.de ←",
    safetyTitle: "إن رأيت أحد هذه",
    safetyBody: "رسم جداري، ملصق، رمز في مكان عام — وثّقه من مسافة آمنة، على ملكية عامة، دون مواجهة أحد. إذا كانت جريمة جارية أو شعرت بعدم الأمان، اتصل بالشرطة أولًا (110). خلاف ذلك، توفّر الخريطة مسار إبلاغ مصمَّمًا لهذا بالضبط.",
    fileBtn: "إبلاغ ←",
    footer: "المصادر: قانون العقوبات الألماني (StGB) المواد 86 و86a، وقانون الجمعيات (Vereinsgesetz). يوثّق هذا حقائق قانونية متاحة للعامة لأغراض التعرّف والسلامة — وهو ليس استشارة قانونية.",
  },
};
