export const AWARENESS: Record<string, any> = {
  en: {
    eyebrow: "Awareness", h1: "Recognizing far-right symbols, gestures, and coded language.",
    lede: "Not a catalog to browse for its own sake — a reference for recognizing what you're looking at, so you can report it, avoid it, or just understand what you saw.",
    whyTitle: "Why this describes rather than shows",
    whyBody: "You won't find images of the symbols here. Text descriptions are enough for recognition, and reproducing the imagery itself — even for education — risks doing the one thing this project exists to stop.",
    symbolsEyebrow: "Banned under § 86a StGB", symbolsTitle: "Symbols and gestures",
    symbolsLede: "Public use or display of these is a criminal offense in Germany, outside narrow exceptions.",
    symbols: [
      { code: "§ 86a StGB", title: "The swastika (Hakenkreuz)", body: "The most widely recognized Nazi symbol. Any orientation, any context outside the legal exceptions above, is covered by the ban — including stylized versions." },
      { code: "§ 86a StGB", title: "SS runes and the death's head (Totenkopf)", body: "The double lightning-bolt Sig rune and skull-and-crossbones insignia are both banned symbols." },
      { code: "§ 86a StGB", title: "The Hitler salute and Sieg Heil", body: "The raised-arm salute and phrase Sieg Heil are both criminalized — not just graphic symbols." },
      { code: "§ 86a StGB", title: "The Reichskriegsflagge", body: "Specific historical war-flag variants (1938 pattern) are banned; context and variant matter." },
    ],
    codesEyebrow: "Coded language", codesTitle: "Numbers and letter codes",
    codesLede: "Numeric substitution ciphers let the same message travel without tripping a filter.",
    codes: [
      { k: "88", v: "H is the 8th letter — HH = Heil Hitler" },
      { k: "18", v: "AH = Adolf Hitler initals" },
      { k: "14 / 1488", v: "The 14 words slogan, often paired with 88" },
      { k: "28", v: "BH — Blood & Honour, banned network" },
    ],
    orgEyebrow: "Organizations", orgTitle: "Banned associations",
    orgBody: "Germany's federal and state governments can ban specific far-right organizations under Vereinsgesetz — continuing to act for a banned association is itself an offense. For the authoritative list, see verfassungsschutz.de.",
    orgLink: "verfassungsschutz.de →",
    safetyTitle: "If you see one of these",
    safetyBody: "Document it from a safe distance, on public property, without confronting anyone. If crime in progress or unsafe, call police (110).",
    fileBtn: "File a report →",
    footer: "Sources: StGB §§ 86, 86a, Vereinsgesetz. Not legal advice.",
  },
  de: {
    eyebrow: "Aufklärung", h1: "Rechtsextreme Symbole, Gesten und Code-Sprache erkennen.",
    lede: "Kein Katalog zum Durchstöbern — ein Nachschlagewerk zum Erkennen.",
    whyTitle: "Warum hier beschrieben statt gezeigt wird",
    whyBody: "Hier finden sich keine Abbildungen. Text reicht zur Erkennung, Bilder zu zeigen riskiert genau das, was verhindert werden soll.",
    symbolsEyebrow: "Verboten nach § 86a StGB", symbolsTitle: "Symbole und Gesten",
    symbolsLede: "Öffentliche Verwendung ist in Deutschland strafbar, mit engen Ausnahmen.",
    symbols: [
      { code: "§ 86a StGB", title: "Das Hakenkreuz", body: "Das bekannteste NS-Symbol. Jede Ausrichtung außerhalb Ausnahmen fällt unter Verbot." },
      { code: "§ 86a StGB", title: "SS-Runen und Totenkopf", body: "Doppelte Blitz-Sig-Rune und Totenkopf-Abzeichen sind verbotene Symbole." },
      { code: "§ 86a StGB", title: "Hitlergruß und Sieg Heil", body: "Erhobener Arm und Sieg Heil sind strafbar." },
      { code: "§ 86a StGB", title: "Reichskriegsflagge", body: "Bestimmte historische Varianten (1938) sind verboten — Kontext entscheidet." },
    ],
    codesEyebrow: "Code-Sprache", codesTitle: "Zahlen- und Buchstabencodes",
    codesLede: "Numerische Chiffren lassen Botschaft als Tattoo/Kennzeichen reisen.",
    codes: [
      { k: "88", v: "H ist der 8. Buchstabe — HH = Heil Hitler" },
      { k: "18", v: "AH = Adolf Hitlers Initialen" },
      { k: "14 / 1488", v: "Die 14 words, oft mit 88" },
      { k: "28", v: "BH — Blood & Honour, verboten" },
    ],
    orgEyebrow: "Organisationen", orgTitle: "Verbotene Vereinigungen",
    orgBody: "Bund/Länder können Organisationen nach Vereinsgesetz verbieten — Fortführen ist Straftat (§20). Aktuelle Liste: verfassungsschutz.de.",
    orgLink: "verfassungsschutz.de →",
    safetyTitle: "Wenn du so etwas siehst",
    safetyBody: "Aus sicherer Entfernung auf öffentlichem Grund dokumentieren, niemanden konfrontieren. Bei Gefahr Polizei 110.",
    fileBtn: "Melden →",
    footer: "Quellen: StGB §§86,86a, Vereinsgesetz. Keine Rechtsberatung.",
  },
}
